junzis/pyModeS

pyModeS/streamer/screen.py

The icao variable is tested for None on line 136 but is not defined if
no flight is known

streamer.screen: fix undefined variable icao on emty flight list

---

pyModeS/streamer/modeslive

The core loop in modeslive is currently busy waiting for updates
I think an update rate at 50Hz is more reasonable and reduces cpu usage.

modeslive: fix hight CPU usage

---

pyModeS/streamer/screen.py

the row is countin from 3 to the window hight, but the idx ist used
as index into the icaos list beginning at 0. the offset is 0 for the
first page. This results in the first 3 flights not shown.

streamer.screen: fix missing flights in view

---

pyModeS/decoder/adsb.py
pyModeS/decoder/bds/bds06.py
pyModeS/decoder/bds/bds09.py

I added two more list elements to `airborne_velocity()` return. The elements are the sources for direction (ground track or magnetic heading) and vertical rate (barometric or GNSS). The positions of the source elements correspond to the pattern of the first three elements.
I also made a modification to `surface_velocity()` to return a six element list. It keeps the same format as for `airborne_velocity()`, but substitutes `'gnd_trk'` for direction source and `None` for vertical speed and its source.

Additional Information Extracted from TC-19/BDS0,9 Messages

---

pyModeS/decoder/common.py
pyModeS/decoder/fastcrc.py
tests/test_common.py

The current CRC function is slow and creates a bottleneck in my current project that has to validate large volumes of messages.
I propose to backport my changes for the future version pyModeS 2.0:
- An updated CRC calculation that computes bitmasks directly
- CRC function now returns integer
- Additional unit test cases

FastCRC - A more efficient CRC calculation

---

pyModeS/extra/tcpclient.py

The TCP BaseClient class is modified to recognize the environment variable `PYMODES_DEBUG`. When the variable is set to `'true'`, the stream will halt execution and provide a traceback rather than restarting. This is for debugging purposes and does not alter the main functionality of the program.
This modification helped me identify erroneous messages from a dump1090 beast feed. Without the error message and break, all I had been provided was `invalid literal for int() with base 2: ''`.
More information on that problem is contained in issue #42.

Add debugging option

---

pyModeS/decoder/bds/bds09.py

If the aircraft velocity message indicates a supersonic subtype (2 or 4), multiply the derived velocity by four. This is in accordance with ICAO document 9871 *Technical Provisions for Mode-S Services and Extended Squitter* table A-2-9a (velocity over ground) and table A-2-9b (airspeed and heading).

Decoder recognizes supersonic velocity subtype

---

pyModeS/decoder/bds/bds08.py

Fixed a bug in bds08.py -> category(msg). The function returns now the right ADS-B emitter category number.

Corrected ADS-B emitter category parsing.

---

.gitignore
pyModeS/decoder/bds/bds06.py
tests/test_bds_inference.py

Hi Junzi Sun,
First of all, great work on the pyModeS project, it is of great help in my coding activities! 
When decoding surface position messages with the receiver reference location in the western hemisphere, I found that these messages were wrongly decoded. This is because the four possible longitude solutions are all positive, between 0 and 360 degrees, whereas the reference location has a negative longitude (i.e. between -180 and 0). Your algorithm always picks the longitude closest to the reference location. For example, when the four possible longitudes are [45, 135, 225, 315] and my reference location is -45, the decoded longitude will be +45.
A one line fix places all four possible longitudes between -180 and +180, before choosing the one that is closest to the reference …

Fix surface positions for negative longitude

---

README.rst

I tried to `pms.adsb.surface_velocity()` as per README with a typecode 19 msg and got an error:
```python
>>> import pyModeS as pms
>>> msg = '8d484966990076b9e0762d5ff92c'
>>> pms.adsb.typecode(msg)
19
>>> pms.adsb.surface_velocity(msg)
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "C:\Users\spi\AppData\Roaming\Python\Python27\site-packages\pyModeS\decoder\bds\bds06.py", line 162, in surface_velocity
raise RuntimeError("%s: Not a surface message, expecting 5<TC<8" % msg)
RuntimeError: 8d484966990076b9e0762d5ff92c: Not a surface message, expecting 5<TC<8
```
so I propose this fix.
I used pyModeS      2.2

moved pms.adsb.surface_velocity under typecode 5-8

---

pyModeS/decoder/common.py

The whole repository is compatible for messages passed as `str` or `bytes` except this single line. I can't find a better way to rewrite this line and yet keep the compatibility, but at least it works.

compatibility with bytes

---

pyModeS/extra/tcpclient.py

Without this change, `modeslive` crashes if no data is available on the socket, which can happen during normal operation of a receiver if no aircraft are in range.
Tested on Python 3.7

Continue reading from socket if no data received

---

pyModeS/extra/tcpclient.py

Hi, a small fix. The `disconnect` call in `TcpClient` can't be called without parameters. A better option is to completely close the socket instead IMHO. The testing main function now also stops the Client explicitly, so the `stop` function gets "tested" each time the main is executed.

Fix invalid socket disconnect call in TcpClient

---

pyModeS/decoder/bds/bds09.py

Hi, this fixes `trk` not being defined in case the branch on line 43 is executed.

Fix UnboundLocalError in airborne_velocity when velocity is zero

---

pyModeS/decoder/__init__.py
pyModeS/decoder/bds/bds62.py

- [Issue "Type Error" #128](https://github.com/junzis/pyModeS/issues/128#issue-1306851214) 
1. The `round(baro, 1)` call on line 277 in bds62.py was being called when `baro` was 'None'. 
2. (minor) Padding in `_print()` wasn't sufficient for the `baro` readout 
3. (minor) Output would display units when value was 'None.'
1. Wrapped the `else` clause with the round call so it was only called if `baro` held a numeric value.
2. Updated the output padding from 20 chars to 28 chars 
3. Added a conditional to remove the "millibars" if `baro` is 'None.'

Bds62 baro rounding fix

---

pyModeS/c_common.pyx
pyModeS/decoder/bds/bds05.py

c_common.py: return -999999 (extremely low, physically impossible) altitude in case altitude is unknown or invalid, bds04.py: convert -999999 altitude to None to better signal an invalid/unknown decoded altitude to the user

Properly return None if altitude could not be decoded

---

pyModeS/extra/tcpclient.py

PiAware devices (developed by FlightAware) receive and process Mode-S messages from aircraft. As a software engineer intern at FlightAware, I learned how to decode the messages processed by PiAware devices and retrieve their RSSI values. RSSI stands for Received Signal Strength Indicator and it indicates how strong a radio signal received by a wireless device is. The RSSI values developed by my function will generally range from 0 to -50 with 0 being the signal at its theoretical peak. The RSSI values returned will be relative to the maximum peak it can achieve and will be in terms of dBFS units.

Added a function that retrieves RSSI values from Mode-S messages received by PiAware devices

---

src/pyModeS/streamer/decode.py

Currently the current definition of the `pms.adsb.nic_v1` is as follows:
- `src/pyModeS/decoder/adsb.py`
```python
def nic_v1(msg: str, NICs: int) -> tuple[int, None | float, None | float]:
"""Calculate NIC, navigation integrity category, for ADS-B version 1
Args:
msg (str): 28 hexdigits string
NICs (int or string): NIC supplement
Returns:
int: NIC, Navigation Integrity Category
int or string: Horizontal Radius of Containment
int or string: Vertical Protection Limit
"""
tc = typecode(msg)
if tc is None or tc < 5 or tc > 22:
raise RuntimeError(
"%s: Not a surface position message (5<TC<8), \
airborne position message (8<TC<19), \
or airborne position with GNSS height (20<TC<22)"
% msg
)
NIC = uncertainty.TC_NICv1_lookup[tc]
if isinstance(NIC, dict):
NIC = NIC[NICs]
d_index = …
```

Fixed error when receiving NICv1 in example decoder due to mismatch in output

---

src/pyModeS/decoder/bds/bds05.py
src/pyModeS/decoder/bds/bds06.py
tests/test_adsb.py

Thank you for this excellent library.
I noticed this problem decoding some ADS-B messages. The local airborne decoding failed is some particular cases.
There seems to be some oddities with the Python modulus operator. E.g.:
```
>>> 30.508474576271183 % 6.101694915254237
6.101694915254235
>>> import math
>>> def mod(x, y):
...     return x - y * math.floor(x / y)
...
>>> mod(30.508474576271183, 6.101694915254237)
0.0
```
Checking the standard (1090 MOPS, Vol.1  DO-260C), section 1.7.5 in Appendix A, shows an equivalent and simpler expression that doesn't require use of a modulus function. I think this should be the preferred approach since it's more accurate and requires less computations.

Fix for a corner-case numerical problem and corresponding unit test.

---

src/pyModeS/streamer/screen.py

The current implementation of `modeslive` on terminal screens creates difficult to read formatting due to floating point precision larger than the defined column widths. This PR makes an adjustment to round floating point numbers to the defined column width to improve readability.  This resolves issue https://github.com/junzis/pyModeS/issues/178
This behavior may have been caused by https://github.com/junzis/pyModeS/pull/147. For visual user output it probably makes sense to at least keep some formatting in the terminal view. This PR does not affect any other internal calculations or the `dump` output.
The logic is:
- Determine if there is a negative sign in the output
- Account for the decimal point
- From the column width, subtract the negative sign, decimal, and one extra space to …

Fix floating point display on terminal output

---

src/pyModeS/streamer/modeslive.py

This fixes an issue preventing pyModeS from being usable on OSX. The root cause of the issue is that the default start method for multiprocessing on OSX is `spawn` which is not compatible with pyModeS. Additionally, as of Python 3.14 `fork` must be specified explicitly. See: https://docs.python.org/3/library/multiprocessing.html#contexts-and-start-methods
There's probably a better way to clean this up however this is the simplest fix for now.
1. Checked OSX (15.2) run
Before:
After
2. Checked Linux run before/after change no difference

Explicitly set multiprocessing start method to fork for OSX support
